# make_partially_linear_dataset_constant { #caml.extensions.synthetic_data.make_partially_linear_dataset_constant }

`extensions.synthetic_data.make_partially_linear_dataset_constant(n_obs=1000, ate=4.0, n_confounders=10, dgp='make_plr_CCDDHNR2018', seed=None, **doubleml_kwargs)`

Generate a partially linear model data generating process with a constant treatment effect (ATE only). The outcome and treatment are both continuous.
The dataset is generated using the `make_plr_CCDDHNR2018` or `make_plr_turrell2018` function from the [`doubleml` package](https://docs.doubleml.org/stable/index.html).

The general form of the data generating process is:

$$
Y_i= \tau_0 D_i + g(\mathbf{X_i})+\epsilon_i
$$
$$
D_i=f(\mathbf{X_i})+\eta_i
$$

where $Y_i$ is the outcome, $D_i$ is the treatment, $\mathbf{X_i}$ are the covariates, $\epsilon_i$ and $\eta_i$ are the error terms, $\tau_0$ is the ATE parameter, $g$ is the outcome function, and $f$ is the treatment function.

See the `doubleml` documentation for more details on the specific functional forms of the data generating process.

As a DAG, the data generating process can be roughly represented as:

<div style="text-align: center;">
```{mermaid}
flowchart TD;
    X((X))-->D((D));
    X((X))-->Y((Y));
    D((D))-->|"τ0"|Y((Y));
    linkStyle 0,1 stroke:black,stroke-width:2px
    linkStyle 1,2 stroke:black,stroke-width:2px
```
</div>

## Parameters

| Name                | Type        | Description                                                                                                                 | Default                  |
|---------------------|-------------|-----------------------------------------------------------------------------------------------------------------------------|--------------------------|
| `n_obs`             | int         | The number of observations to generate. Default is 1000.                                                                    | `1000`                   |
| `ate`               | float       | The average treatment effect. Default is 4.0.                                                                               | `4.0`                    |
| `n_confounders`     | int         | The number of confounders to generate. Default is 10.                                                                       | `10`                     |
| `dgp`               | str         | The data generating process to use. Default is "make_plr_CCDDHNR20". Can be "make_plr_CCDDHNR20" or "make_plr_turrell2018". | `'make_plr_CCDDHNR2018'` |
| `seed`              | int \| None | The seed to use for the random number generator. Default is None.                                                           | `None`                   |
| `**doubleml_kwargs` |             | Additional keyword arguments to pass to the data generating process.                                                        | `{}`                     |

## Returns

| Type         | Description                                                                                 |
|--------------|---------------------------------------------------------------------------------------------|
| pd.DataFrame | The generated dataset where y is the outcome, d is the treatment, and X are the covariates. |
| float        | The true average treatment effect.                                                          |

## Examples

```python
>>> from caml.extensions.synthetic_data import make_partially_linear_dataset_constant
>>> df, true_ate = make_partially_linear_dataset_constant(n_obs=1000, ate=4.0, n_confounders=10, dgp="make_plr_CCDDHNR2018", seed=1)
```