project:
  type: website
  output-dir: _site
  preview:
    port: 4848

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles/styles.css
    toc: true
    toc-depth: 5
    toc-expand: 2
    table-scroll: true
    include-in-header: version-switcher.html
    highlight-style: github

website:
  title: CaML - Causal ML
  favicon: assets/logo_no_text.svg
  page-navigation: true
  open-graph: true
  back-to-top-navigation: true
  repo-url: https://github.com/jakepenzak/caml
  repo-actions: [edit, issue]
  repo-branch: main
  repo-subdir: docs
  issue-url: https://github.com/jakepenzak/caml/issues/new

  navbar:
    logo: "assets/logo_no_text.svg"
    title: false
    background: "white"
    search: true
    border: true
    tools:
      - icon: github
        menu:
          - text: Source code
            url: https://github.com/jakepenzak/caml
          - text: Report Issue
            url: https://github.com/jakepenzak/caml/issues/new

    left:
      - sidebar:Home
      - sidebar:Concepts
      - sidebar:Examples
      - sidebar:API_Reference

    right:
      - sidebar:Contributors

  sidebar:
    - id: ""
    - id: Home
      title: "Home"
      style: floating
      contents:
        - text: Welcome!
          href: index.qmd
        - 01_Home/installation.qmd
        - 01_Home/quickstart.qmd
    - id: Concepts
      title: "Concepts"
      style: floating
      contents:
        - 02_Concepts/motivation.qmd
        - 02_Concepts/estimators.qmd
        - 02_Concepts/scorers.qmd
        - 02_Concepts/references.qmd
    # - id: Examples
    #   title: "Examples"
    #   style: floating
    # contents: 03_Examples/*
    - id: API_Reference
      title: "Reference"
      style: floating
      contents:
        - 04_Reference/index.qmd
        - 04_Reference/support_matrix.qmd
    - id: Contributors
      title: "Contributors"
      style: floating
      contents:
        - 05_Contributors/getting_started.qmd
        - 05_Contributors/environment.qmd
        - 05_Contributors/documentation.qmd
        - 05_Contributors/testing.qmd
        - 05_Contributors/conventional_commits.qmd

  page-footer:
    border: false
    left: "© Copyright 2026, Jacob Pieniazek"
    right: |
      Powered by: [![](/assets/external_logos/quarto.png){width=85px}](https://quarto.org/)

quartodoc:
  package: caml
  dir: 04_Reference
  title: API Reference
  sidebar: 04_Reference/_sidebar.yml
  source_dir: ../caml
  renderer:
    style: _extensions.renderer_with_source.py
  sections:
    - title: CaML Core
      desc: "`caml` \n\n Core CaML modules."

    - subtitle: AutoML
      desc: "`caml.automl` \n\n Primary AutoML Estimator."
      package: caml.automl

    - subtitle: Data
      desc: "`caml.data` \n\n CaML Data Containers and schemas."
      package: caml.data
      contents:
        - name: dataset
          member_order: source
        - name: data_enums
          member_order: source

    - subtitle: Estimators
      desc: "`caml.estimators` \n\n Native and wrapped CATE estimators."
      package: caml.estimators
      contents:
        - name: base_estimator
          member_order: source
          member_options:
            include_private: true
        - name: dml
          member_order: source
          member_options:
            include_inherited: true
          members:
            - WrappedLinearDML
            - WrappedSparseLinearDML
            - WrappedCausalForestDML
            - WrappedNonParamDML
            - WrappedKernelDML
        - name: dr
          member_order: source
          member_options:
            include_inherited: true
          members:
            - WrappedDRLearner
            - WrappedLinearDRLearner
            - WrappedSparseLinearDRLearner
            - WrappedForestDRLearner
        - name: meta
          member_order: source
          member_options:
            include_inherited: true
          members:
            - WrappedSLearner
            - WrappedTLearner
            - WrappedXLearner
        - name: orf
          member_order: source
          member_options:
            include_inherited: true
          members:
            - WrappedDMLOrthoForest
            - WrappedDROrthoForest

    - subtitle: Scorers
      desc: "`caml.scorers` \n\n Primary CATE scoring & validation metrics."
      package: caml.scorers
      contents:
        - name: base_scorer
          member_order: source
          member_options:
            include_private: true
        - name: pehe
          member_order: source
          member_options:
            include_private: true
            include_inherited: true
        - name: r_loss
          member_order: source
          member_options:
            include_private: true
            include_inherited: true
        - name: dr_loss
          member_order: source
          member_options:
            include_private: true
            include_inherited: true
        - name: q_stat
          member_order: source
          member_options:
            include_private: true
            include_inherited: true

    - subtitle: Registry
      desc: "`caml.registry` \n\n AutoCATE estimator registry."
      package: caml.registry
      contents:
        - name: registry
          member_order: source
        - name: registry_enums
          member_order: source

    - subtitle: Nuisance
      desc: "`caml.nuisance` \n\n First-stage nuisance estimation objects."
      package: caml.nuisance
      contents:
        - name: spec
          member_order: source
        - name: tuner
          member_order: source

    - subtitle: Samplers
      desc: "`caml.samplers` \n\n Primary CATE sampling utilities and objects."
      package: caml.samplers
      contents:
        - name: cross_fit
          member_order: source
        - name: splitters
          member_order: source

    - subtitle: Inference
      desc: "`caml.inference` \n\n Inference objects and schemas."
      package: caml.inference
      contents:
        - name: results
          member_order: source
        - name: inference_enums
          member_order: source

    - title: CaML Extensions
      desc: "`caml.extensions` \n\n Additional utilities and tools for working in CaML."

    - subtitle: Synthetic Data Generation
      desc: "`caml.extensions.synthetic_data` <br> <br> Synthetic data generation utilities for CaML."
      package: caml.extensions
      contents:
        - name: synthetic_data
          member_order: source

    - subtitle: Plots
      desc: "`caml.extensions.plots` <br> <br> Plotting utilities for CaML."
      package: caml.extensions
      contents:
        - name: plots
          member_order: source

metadata-files:
  - _sidebar.yml
