# FastLeastSquares { #caml.FastLeastSquares }

```python
FastLeastSquares(
    self,
    Y,
    T,
    G=None,
    X=None,
    W=None,
    *,
    discrete_treatment=True,
    engine='cpu',
)
```

FastLeastSquares is a fast implementation of the Least Squares estimator designed specifically with Causal Inference in mind.

This estimator estimates a standard linear regression model for any number of continuous or binary outcomes and a single binary treatment,
and provides estimates for the Average Treatment Effects (ATEs) and Group Average Treatment Effects (GATEs) out of the box. Additionally,
methods are provided for estimating a specific Conditional Average Treatment Effect (CATE), as well as individual Conditional Average Treatment
Effects (CATEs) for a group of observations.

This class leverages JAX for fast numerical computations, which can be installed using `pip install caml[jax]`, defaulting to NumPy if JAX is not
available. For GPU acceleration, install JAX with GPU support using `pip install caml[jax-gpu]`.

**Outcome/Treatment Type Support Matrix**
<center>
| Outcome     | Treatment   | Support     | Missing    |
| ----------- | ----------- | ----------- | ---------- |
| Continuous  | Binary      | ✅Full      |            |
| Continuous  | Continuous  | ❌Not yet   |            |
| Continuous  | Categorical | ❌Not yet   |            |
| Binary      | Binary      | ✅Full      |            |
| Binary      | Continuous  | ❌Not yet   |            |
| Binary      | Categorical | ❌Not yet   |            |
| Categorical | Binary      | ❌Not yet   |            |
| Categorical | Continuous  | ❌Not yet   |            |
| Categorical | Categorical | ❌Not yet   |            |
</center>

## Parameters {.doc-section .doc-section-parameters}

| Name               | Type                    | Description                                                                                                                                                                  | Default    |
|--------------------|-------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| Y                  | Iterable\[str\]         | A list of outcome variable names.                                                                                                                                            | _required_ |
| T                  | str                     | The treatment variable name.                                                                                                                                                 | _required_ |
| G                  | Iterable\[str\] \| None | A list of group variable names, by default None. These will be the groups for which GATEs will be estimated.                                                                 | `None`     |
| X                  | Iterable\[str\] \| None | A list of covariate variable names, by default None. These will be the covariates for which heterogeneity/CATEs can be estimated.                                            | `None`     |
| W                  | Iterable\[str\] \| None | A list of instrument variable names, by default None. These will be the additional covariates not used for modeling heterogeneity/CATEs.                                     | `None`     |
| discrete_treatment | bool                    | Whether the treatment is discrete, by default True                                                                                                                           | `True`     |
| engine             | str                     | The engine to use for computation, by default "cpu". Can be "cpu" or "gpu". Note "gpu" requires JAX to be installed, which can be installed via `pip install caml[jax-gpu]`. | `'cpu'`    |

## Attributes {.doc-section .doc-section-attributes}

| Name               | Type   | Description                                                                                                                                                                 |
|--------------------|--------|-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| Y                  |        | A list of outcome variable names.                                                                                                                                           |
| T                  |        | The treatment variable name.                                                                                                                                                |
| G                  |        | A list of group variable names, by default None. These will be the groups for which GATEs will be estimated.                                                                |
| X                  |        | A list of covariate variable names, by default None. These will be the covariates for which heterogeneity/CATEs can be estimated.                                           |
| W                  |        | A list of instrument variable names, by default None. These will be the additional covariates not used for modeling heterogeneity/CATEs.                                    |
| discrete_treatment |        | Whether the treatment is discrete, by default True                                                                                                                          |
| engine             |        | The engine to use for computation, by default "cpu". Can be "cpu" or "gpu". Note "gpu" requires JAX to be installed, which can be installed via `pip install caml[jax-gpu]` |
| formula            |        | The formula leveraged for design matrix creation via Patsy.                                                                                                                 |
| results            |        | A dictionary containing the results of the fitted model & estimated ATEs/GATEs.                                                                                             |

## Methods

| Name | Description |
| --- | --- |
| [fit](#caml.FastLeastSquares.fit) | Fits the regression model on the provided data and estimates ATEs and GATEs. |

### fit { #caml.FastLeastSquares.fit }

```python
FastLeastSquares.fit(data, n_jobs=-1)
```

Fits the regression model on the provided data and estimates ATEs and GATEs.

#### Parameters {.doc-section .doc-section-parameters}

| Name   | Type          | Description                                                                                                                                                                                    | Default    |
|--------|---------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| data   | DataFrameLike | Input data to fit the model on. Supported formats: pandas DataFrame, PySpark DataFrame, Polars DataFrame, or Any object with toPandas() or to_pandas() method                                  | _required_ |
| n_jobs | int           | The number of jobs to use for parallel processing in the estimation of GATEs. Defaults to -1, which uses all available processors. If getting OOM errors, try setting n_jobs to a lower value. | `-1`       |