name: Build & Publish Docs

on:
  pull_request:
    types: [closed]
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest
    if: >
      github.event.pull_request.merged == true &&
      !contains(join(github.event.pull_request.labels.*.name, ','), 'type: release')

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@0c5e2b8115b80b4c7c5ddf6ffdd634974642d182
        with:
          version: ${{ vars.UV_VERSION }}

      - name: Create environment
        run: uv sync --all-groups --frozen

      - name: Render & Publish Docs
        shell: bash -l {0}
        run: |
          set -e
          source .venv/bin/activate
          bash docs/marimo_examples_to_quarto.sh
          quartodoc build --config docs/_quarto.yml
          quarto render docs/ --output-dir ../dev

      - name: Checkout api-docs branch
        uses: actions/checkout@v4
        with:
          ref: api-docs

      - name: Copy dev into _site directory
        run: cp dev versions.json CNAME _site/ -r

      - name: Commit and push dev & _site directory
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add dev _site
          git commit -m "Update dev directory"
          git push origin api-docs

      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "_site"

      - name: Deploy to Github Pages 🚀
        id: deployment
        uses: actions/deploy-pages@v4
