name: Run Tests & Update Badge

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Install uv
        uses: astral-sh/setup-uv@v2
        with:
          version: "0.4.10"

      - name: Install Python
        run: uv python install

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest tests

      - name: Check for changes & Push if exist
        id: git_check
        run: |
          if git diff --quiet; then
            echo "No changes to commit"
          else
            git config --global user.name 'GitHub Action'
            git config --global user.email 'action@github.com'
            git add .
            git commit -m "Update Test Badge"
            git push origin ${{ github.head_ref }}
          fi
